Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

import core.urls

urlpatterns = [
                  # add all the urls at the core/ urls
                  path('', include('core.urls')),
                  # all the urls will be there which are in the item/url.py file
                  path('items/', include('item.url')),
                  # add the all the urls at the dashboard
<<<<<<< HEAD
                  path('dashboard/', include('dashboard.urls')),
=======
                  path('dashboard/',include('dashboard.urls')),
>>>>>>> origin/main
                  path('admin/', admin.site.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_view.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm),
         name='login'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

dashboard/models.py
from django.db import models

# Create your models here.

item/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=255)

    # can add option for the model
    class Meta:
        # iterable item - sorting the rows
        ordering = ('name',)
        verbose_name_plural = 'catogries'

    def __str__(self):
        return self.name


# creating the item db model
class items(models.Model):
    # adding the frogine key of the category
    item_cat = models.ForeignKey(Category, related_name='item', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    # accepting the null and blank values
    discription = models.TextField(blank=True, null=True)
    # creating the field to upload the images
    item_img = models.ImageField(upload_to='item_image', blank=True, null=True)
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    # adding the frogine key of the user
    created_by = models.ForeignKey(User, related_name='item', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    # can add option for the model
    class Meta:
        # iterable item - sorting the rows
        ordering = ('name',)
        verbose_name_plural = 'items'

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


# creating the class for the log in
class LoginForm(AuthenticationForm):
    fields = ('username', 'password')


# creating the class for the signup
class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'password1', 'password2')

item/forms.py
from django import forms
from .models import items


#adding the fields to the form 
class NewItemForm(forms.ModelForm):
    class Meta:
        model = items
        fields = {'item_cat', 'name', 'discription', 'price', 'item_img', }


class EditItemForm(forms.ModelForm):
    class Meta:
        model = items
        fields = { 'name', 'discription', 'price', 'item_img', 'is_sold'}

core/views.py
from django.shortcuts import render, redirect
from item.models import Category, items
from .forms import SignupForm


# Create your views here.

def index(request):
    item = items.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': item,
    })


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })

dashboard/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404

from item.models import items


@login_required
def index(request):
    Item = items.objects.filter(created_by=request.user)
    return render(request, 'dashboard/index.html', {
        'item': Item,
    })

item/views.py
from collections import UserDict
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render, get_object_or_404
from .models import items, Category
from item.forms import NewItemForm, EditItemForm
from django.db.models import Q


def search_item(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    serch_result = items.objects.filter(is_sold=False)

    if category_id:
        serch_result = items.objects.filter(item_cat_id=category_id)

    if query:
        serch_result = serch_result.filter(name__icontains=query | Q(discription__icontains=query))

    return render(request, 'item/browse.html', {
        'item': serch_result,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })


# Create your views here.
def detail(request, pk):
    item = get_object_or_404(items, pk=pk)

    # getting the related item by searching the item category id 95
    related_item = items.objects.filter(item_cat_id=item.item_cat, is_sold=False).exclude(pk=pk)[0:3]
    # render the template
    return render(request, 'detail.html', {
        'item': item,
        'related_item': related_item
    })


# adding the new item

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            newItem = form.save(commit=False)
            newItem.created_by = request.user
            newItem.save()

            return redirect('/')

    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'New Item',
    })


@login_required
def edit(request, pk):
    item = get_object_or_404(items, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

        return redirect('/')

    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit Item',
    })


@login_required
def delete(request, pk):
    # getting the data from the database
    item = get_object_or_404(items, pk=pk, created_by=request.user)
    item.delete()

    return redirect('dashboard:index')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
</head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin-top: 1%; margin-right: 1%; margin-left: 1%; border-radius: 10px">
  <a class="navbar-brand" href="#">Paddle</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'item:new' %}">New Item <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'item:search_item' %}">Browse</a>
      </li>
        {% if request.user.is_authenticated %}
             <li class="nav-item">
        <a class="nav-link" href="#">
            <button class="-btn btn-info">Inbox</button>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url  'dashboard:index' %}">
            <button class="-btn btn-success">Dashboard</button>
        </a>
      </li>
            <li class="nav-item">
        <a class="nav-link" href="#">
            <button class="-btn btn-danger">Logout</button>
        </a>
      </li>
        {% else %}
            <li class="nav-item">
        <a class="nav-link" href="{% url 'core:signup' %}">
            <button class="-btn btn-success">Sign Up</button>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'core:login' %}">
            <button class="-btn btn-warning">Login</button>
        </a>
      </li>
        {% endif %}
    </ul>
  </div>
</nav>
    </div>
    {% block content%}

    {% endblock %}

<style type="text/css">
    .footer-dark {
  padding:50px 0;
  color:#f0f9ff;
  background-color:#282d32;
}

.footer-dark h3 {
  margin-top:0;
  margin-bottom:12px;
  font-weight:bold;
  font-size:16px;
}

.footer-dark ul {
  padding:0;
  list-style:none;
  line-height:1.6;
  font-size:14px;
  margin-bottom:0;
}

.footer-dark ul a {
  color:inherit;
  text-decoration:none;
  opacity:0.6;
}

.footer-dark ul a:hover {
  opacity:0.8;
}

@media (max-width:767px) {
  .footer-dark .item:not(.social) {
    text-align:center;
    padding-bottom:20px;
  }
}

.footer-dark .item.text {
  margin-bottom:36px;
}

@media (max-width:767px) {
  .footer-dark .item.text {
    margin-bottom:0;
  }
}

.footer-dark .item.text p {
  opacity:0.6;
  margin-bottom:0;
}

.footer-dark .item.social {
  text-align:center;
}

@media (max-width:991px) {
  .footer-dark .item.social {
    text-align:center;
    margin-top:20px;
  }
}

.footer-dark .item.social > a {
  font-size:20px;
  width:36px;
  height:36px;
  line-height:36px;
  display:inline-block;
  text-align:center;
  border-radius:50%;
  box-shadow:0 0 0 1px rgba(255,255,255,0.4);
  margin:0 8px;
  color:#fff;
  opacity:0.75;
}

.footer-dark .item.social > a:hover {
  opacity:0.9;
}

.footer-dark .copyright {
  text-align:center;
  padding-top:24px;
  opacity:0.3;
  font-size:13px;
  margin-bottom:0;
}

</style>

    <div class="footer-dark" style="justify-content: end">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Services</h3>
                        <ul>
                            <li><a href="#">Web design</a></li>
                            <li><a href="#">Development</a></li>
                            <li><a href="#">Hosting</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Company Name</h3>
                        <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">Company Name © 2018</p>
            </div>
        </footer>
    </div>
</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %} Welcome {% endblock %}
{% block  content%}
    <h1>This is contact</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block title %} Welcome {% endblock %}
{% block  content%}
    <center>
        <h1 style="font-family: 'Arial Unicode 3S'; margin-top: 3%; margin-bottom: 3%">New Item</h1>
    </center>
    <style>
    .card-container {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-evenly;
        padding-bottom: 5%;
    }

    .card {
      width: calc(25% - 10px);
      margin: 5px;
      background-color: #f0f0f0;
      padding: 10px;
      box-sizing: border-box;
     height: 350px;
     position: relative;
     overflow: visible;
     box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    }

.card-img {
    background-color: aliceblue;
 height: 80%;
 width: 100%;
 border-radius: .5rem;
}

.card-info {
 padding-top: 10%;
}

svg {
 width: 20px;
 height: 20px;
}

.card-footer {
 width: 100%;
 display: flex;
 justify-content: space-between;
 align-items: center;
 padding-top: 10px;
 border-top: 1px solid #ddd;
}

/*Text*/
.text-title {
 font-weight: 900;
 font-size: 1.2em;
 line-height: 1.5;
    padding-left: 5%;
}

.text-body {
 font-size: .9em;
 padding-bottom: 10px;
    padding-left: 5%;
}

/*Button*/
.card-button {
 border: 1px solid #252525;
 display: flex;
 padding: .3em;
 cursor: pointer;
 border-radius: 50px;
 transition: .3s ease-in-out;
}


.card-button:hover {
 border: 1px solid #ffcaa6;
 background-color: #ffcaa6;
}

  </style>
     <div class="card-container">
    {% for item in items %}

              <div class="card">

                      <div class="card-img">
                      <center>
                          <a href="{% url 'item:detail' item.id %}">
                          <img src="{{ item.item_img.url }}" alt="product image" style="height: 150px">
                              </a>
                      </center>
                  </div>
                  <div class="card-info">
                    <p class="text-title">{{ item.name }} </p>
                    <p class="text-body">{{ item.discription }}</p>
                  </div>
                  <div class="card-footer">
                  <span class="text-title">${{ item.price }}</span>
                  <div class="card-button">
                    <svg class="svg-icon" viewBox="0 0 20 20">
                      <path d="M17.72,5.011H8.026c-0.271,0-0.49,0.219-0.49,0.489c0,0.271,0.219,0.489,0.49,0.489h8.962l-1.979,4.773H6.763L4.935,5.343C4.926,5.316,4.897,5.309,4.884,5.286c-0.011-0.024,0-0.051-0.017-0.074C4.833,5.166,4.025,4.081,2.33,3.908C2.068,3.883,1.822,4.075,1.795,4.344C1.767,4.612,1.962,4.853,2.231,4.88c1.143,0.118,1.703,0.738,1.808,0.866l1.91,5.661c0.066,0.199,0.252,0.333,0.463,0.333h8.924c0.116,0,0.22-0.053,0.308-0.128c0.027-0.023,0.042-0.048,0.063-0.076c0.026-0.034,0.063-0.058,0.08-0.099l2.384-5.75c0.062-0.151,0.046-0.323-0.045-0.458C18.036,5.092,17.883,5.011,17.72,5.011z"></path>
                      <path d="M8.251,12.386c-1.023,0-1.856,0.834-1.856,1.856s0.833,1.853,1.856,1.853c1.021,0,1.853-0.83,1.853-1.853S9.273,12.386,8.251,12.386z M8.251,15.116c-0.484,0-0.877-0.393-0.877-0.874c0-0.484,0.394-0.878,0.877-0.878c0.482,0,0.875,0.394,0.875,0.878C9.126,14.724,8.733,15.116,8.251,15.116z"></path>
                      <path d="M13.972,12.386c-1.022,0-1.855,0.834-1.855,1.856s0.833,1.853,1.855,1.853s1.854-0.83,1.854-1.853S14.994,12.386,13.972,12.386z M13.972,15.116c-0.484,0-0.878-0.393-0.878-0.874c0-0.484,0.394-0.878,0.878-0.878c0.482,0,0.875,0.394,0.875,0.878C14.847,14.724,14.454,15.116,13.972,15.116z"></path>
                    </svg>
                  </div>
                  </div>

              </div>

    {% endfor %}
     </div>

    <section>
        <div>
            <center>
                <h1 style="font-family: 'Arial Unicode 3S'; margin-top: 3%; margin-bottom: 3%">Categories</h1>
            </center>

        <style>
            .card {
  width: 190px;
  height: 254px;
  transition: all 0.2s;
  position: relative;
  cursor: pointer;
}

.card-inner {
  width: inherit;
  height: inherit;
  background: rgba(255,255,255,.05);
  box-shadow: 0 0 10px rgba(0,0,0,0.25);
  backdrop-filter: blur(10px);
  border-radius: 8px;
}

.card:hover {
  transform: scale(1.04) rotate(1deg);
}

.circle {
  width: 100px;
  height: 100px;
  background: radial-gradient(#b0e633, #53ef7d);
  border-radius: 50%;
  position: absolute;
  animation: move-up6 2s ease-in infinite alternate-reverse;
}

.circle:nth-child(1) {
  top: -25px;
  left: -25px;
}

.circle:nth-child(2) {
  bottom: -25px;
  right: -25px;
  animation-name: move-down1;
}

@keyframes move-up6 {
  to {
    transform: translateY(-10px);
  }
}

@keyframes move-down1 {
  to {
    transform: translateY(10px);
  }
}
        </style>
            <div class="card-container">
    {% for category in categories %}
        <div class="card">
            <div class="circle"></div>
            <div class="circle"></div>
            <div class="card-inner">
                <p class="text-title" style="margin-top: 50%; margin-left: 25%">{{ category.name }} : <br> {{ category.item.count }} items </p>
            </div>
        </div>
    {% endfor %}
    </div>
        </div>
    </section>


    
{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% block titlel %}
Login
{% endblock %}
{% block content %}
    <style>
    button {
  font-family: Arial, Helvetica, sans-serif;
  font-weight: bold;
  color: white;
  background-color: #171717;
  padding: 1em 2em;
  border: none;
  border-radius: .6rem;
  position: relative;
  cursor: pointer;
  overflow: hidden;
}

button span:not(:nth-child(6)) {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  height: 30px;
  width: 30px;
  background-color: #0c66ed;
  border-radius: 50%;
  transition: .6s ease;
}

button span:nth-child(6) {
  position: relative;
}

button span:nth-child(1) {
  transform: translate(-3.3em, -4em);
}

button span:nth-child(2) {
  transform: translate(-6em, 1.3em);
}

button span:nth-child(3) {
  transform: translate(-.2em, 1.8em);
}

button span:nth-child(4) {
  transform: translate(3.5em, 1.4em);
}

button span:nth-child(5) {
  transform: translate(3.5em, -3.8em);
}

button:hover span:not(:nth-child(6)) {
  transform: translate(-50%, -50%) scale(4);
  transition: 1.5s ease;
}

    </style>
    <center>
     <h1 style="padding-top: 5%; padding-bottom: 1%">Login</h1>
    </center>
    <div style="padding-left: 25%; padding-bottom: 10%">
    <form method="POST" action=".">
     {% csrf_token %}
        {{ form.non_field_errors }}
    {{ form.as_p }}

    {% if form.error or form.non_field_errors %}
    <div>
        {% for field in form %}
            {{ form.errors }}
        {% endfor %}
        {{ form.non_field_errors }}
    </div>
{% endif %}

<button>
    <span class="circle1"></span>
    <span class="circle2"></span>
    <span class="circle3"></span>
    <span class="circle4"></span>
    <span class="circle5"></span>
    <span class="text">Submit</span>
</button>
    </form>
    </div>
{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}
{% block titlel %}
Sign Up
{% endblock %}
{% block content %}
    <style>
    button {
  font-family: Arial, Helvetica, sans-serif;
  font-weight: bold;
  color: white;
  background-color: #171717;
  padding: 1em 2em;
  border: none;
  border-radius: .6rem;
  position: relative;
  cursor: pointer;
  overflow: hidden;
}

button span:not(:nth-child(6)) {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
  height: 30px;
  width: 30px;
  background-color: #0c66ed;
  border-radius: 50%;
  transition: .6s ease;
}

button span:nth-child(6) {
  position: relative;
}

button span:nth-child(1) {
  transform: translate(-3.3em, -4em);
}

button span:nth-child(2) {
  transform: translate(-6em, 1.3em);
}

button span:nth-child(3) {
  transform: translate(-.2em, 1.8em);
}

button span:nth-child(4) {
  transform: translate(3.5em, 1.4em);
}

button span:nth-child(5) {
  transform: translate(3.5em, -3.8em);
}

button:hover span:not(:nth-child(6)) {
  transform: translate(-50%, -50%) scale(4);
  transition: 1.5s ease;
}

    </style>
    <center>
     <h1 style="padding-top: 5%; padding-bottom: 1%">Sign Up</h1>
    </center>
    <div style="padding-left: 25%; padding-bottom: 10%">
    <form method="POST" action=".">
     {% csrf_token %}
        {{ form.non_field_errors }}
    {{ form.as_p }}

    {% if form.error or form.non_field_errors %}
    <div>
        {% for field in form %}
            {{ form.errors }}
        {% endfor %}
        {{ form.non_field_errors }}
    </div>
{% endif %}

<button>
    <span class="circle1"></span>
    <span class="circle2"></span>
    <span class="circle3"></span>
    <span class="circle4"></span>
    <span class="circle5"></span>
    <span class="text">Submit</span>
</button>
    </form>
    </div>
{% endblock %}

dashboard/templates/dashboard/index.html
{% extends 'core/base.html' %}
{% block title %} My items {% endblock %}
{% block  content%}
    <center>
        <h1 style="font-family: 'Arial Unicode 3S'; margin-top: 3%; margin-bottom: 3%">New Item</h1>
    </center>
    <style>
    .card-container {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-evenly;
        padding-bottom: 5%;
    }

    .card {
      width: calc(25% - 10px);
      margin: 5px;
      background-color: #f0f0f0;
      padding: 10px;
      box-sizing: border-box;
     height: 350px;
     position: relative;
     overflow: visible;
     box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
    }

.card-img {
    background-color: aliceblue;
 height: 80%;
 width: 100%;
 border-radius: .5rem;
}

.card-info {
 padding-top: 10%;
}

svg {
 width: 20px;
 height: 20px;
}

.card-footer {
 width: 100%;
 display: flex;
 justify-content: space-between;
 align-items: center;
 padding-top: 10px;
 border-top: 1px solid #ddd;
}

/*Text*/
.text-title {
 font-weight: 900;
 font-size: 1.2em;
 line-height: 1.5;
    padding-left: 5%;
}

.text-body {
 font-size: .9em;
 padding-bottom: 10px;
    padding-left: 5%;
}

/*Button*/
.card-button {
 border: 1px solid #252525;
 display: flex;
 padding: .3em;
 cursor: pointer;
 border-radius: 50px;
 transition: .3s ease-in-out;
}


.card-button:hover {
 border: 1px solid #ffcaa6;
 background-color: #ffcaa6;
}

  </style>
     <div class="card-container">
    {% for item in item %}

              <div class="card">

                      <div class="card-img">
                      <center>
                          <a href="{% url 'item:detail' item.id %}">
                          <img src="{{ item.item_img.url }}" alt="product image" style="height: 150px">
                              </a>
                      </center>
                  </div>
                  <div class="card-info">
                    <p class="text-title">{{ item.name }} </p>
                    <p class="text-body">{{ item.discription }}</p>
                  </div>
                  <div class="card-footer">
                  <span class="text-title">${{ item.price }}</span>
                  <div class="card-button">
                    <svg class="svg-icon" viewBox="0 0 20 20">
                      <path d="M17.72,5.011H8.026c-0.271,0-0.49,0.219-0.49,0.489c0,0.271,0.219,0.489,0.49,0.489h8.962l-1.979,4.773H6.763L4.935,5.343C4.926,5.316,4.897,5.309,4.884,5.286c-0.011-0.024,0-0.051-0.017-0.074C4.833,5.166,4.025,4.081,2.33,3.908C2.068,3.883,1.822,4.075,1.795,4.344C1.767,4.612,1.962,4.853,2.231,4.88c1.143,0.118,1.703,0.738,1.808,0.866l1.91,5.661c0.066,0.199,0.252,0.333,0.463,0.333h8.924c0.116,0,0.22-0.053,0.308-0.128c0.027-0.023,0.042-0.048,0.063-0.076c0.026-0.034,0.063-0.058,0.08-0.099l2.384-5.75c0.062-0.151,0.046-0.323-0.045-0.458C18.036,5.092,17.883,5.011,17.72,5.011z"></path>
                      <path d="M8.251,12.386c-1.023,0-1.856,0.834-1.856,1.856s0.833,1.853,1.856,1.853c1.021,0,1.853-0.83,1.853-1.853S9.273,12.386,8.251,12.386z M8.251,15.116c-0.484,0-0.877-0.393-0.877-0.874c0-0.484,0.394-0.878,0.877-0.878c0.482,0,0.875,0.394,0.875,0.878C9.126,14.724,8.733,15.116,8.251,15.116z"></path>
                      <path d="M13.972,12.386c-1.022,0-1.855,0.834-1.855,1.856s0.833,1.853,1.855,1.853s1.854-0.83,1.854-1.853S14.994,12.386,13.972,12.386z M13.972,15.116c-0.484,0-0.878-0.393-0.878-0.874c0-0.484,0.394-0.878,0.878-0.878c0.482,0,0.875,0.394,0.875,0.878C14.847,14.724,14.454,15.116,13.972,15.116z"></path>
                    </svg>
                  </div>
                  </div>

              </div>

    {% endfor %}
     </div>
{% endblock %}